name: $(SourceBranchName)-$(date:yyyyMMdd)-build$(rev:r)

trigger:
  batch: false
  branches:
    include: ["master"]
  paths:
    exclude: ["README.md"]

pr:
  branches:
    include: ["master"]
  paths:
    exclude: ["README.md"]

jobs:
  - job: phase_1
    displayName: "Phase 1"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: GoTool@0
        displayName: 'Use Go 1.12'
        inputs:
          version: 1.12

      - task: Bash@3
        displayName: 'Bash Script'
        inputs:
          targetType: filePath
          filePath: 'azure-pipelines.sh'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact'
        inputs:
          ArtifactName: 'autopeer'
