package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"time"
)

func generator_bird1(conf *config, outputPath *string) {
	var err error

	log.Println("Generating bird v1 config files...")

	// create output files
	configFile4, err := os.Create(path.Join(*outputPath, "autopeer4.conf"))
	hardFail(err)
	defer configFile4.Close()
	configFile6, err := os.Create(path.Join(*outputPath, "autopeer6.conf"))
	hardFail(err)
	defer configFile6.Close()

	// write common prefix
	t := time.Now()
	prefix := fmt.Sprintf("# Generated by AutoPeer\n# Format: Bird v1\n# Generated at: %s\n\n", t.Format("2006-01-02 15:04:05"))
	_, err = fmt.Fprint(configFile4, prefix)
	hardFail(err)
	_, err = fmt.Fprint(configFile6, prefix)
	hardFail(err)

	// write BGP session info
	for _, iface := range conf.Interfaces {
		for _, peer := range iface.Peers {
			for _, session := range peer.BgpSessions {
				var configFile io.Writer
				if session.ipv6 == false {
					configFile = configFile4
				} else {
					configFile = configFile6
				}

				_, err = fmt.Fprintf(configFile, "protocol bgp %s ", session.Name)
				hardFail(err)
				if len(session.Template) > 0 {
					_, err = fmt.Fprintf(configFile, "from %s {\n", session.Template)
					hardFail(err)
				} else {
					_, err = fmt.Fprintf(configFile, "{\n")
					hardFail(err)
				}

				if len(session.Table) > 0 {
					_, err = fmt.Fprintf(configFile, "    table %s;\n", session.Table)
					hardFail(err)
				}

				_, err = fmt.Fprintf(configFile, "    local as %d;\n", conf.Asn)
				hardFail(err)

				_, err = fmt.Fprintf(configFile, "    neighbor %s as %d;\n", session.PeerEndpoint, session.Asn)
				hardFail(err)

				if session.MultiHop == 1 {
					_, err = fmt.Fprint(configFile, "    direct;\n")
					hardFail(err)
				}
				if session.MultiHop > 1 {
					_, err = fmt.Fprintf(configFile, "    multihop %d;\n", session.MultiHop)
					hardFail(err)
				}

				_, err = fmt.Fprint(configFile, "}\n\n")
				hardFail(err)
			}
		}
	}
}
